---
- hosts: db-vms
  tasks:
     - name: install epel-release
       yum: name=epel-release state=present update_cache=yes
     - name: install mariadb-server
       yum: name=mariadb-server state=present update_cache=yes
     - name: ensure mariadb started
       service: name=mariadb state=started enabled=yes
